system-ghc: true
nix:
  enable: false
  packages:
    - graphviz
    - imagemagick
    - texlive.combined.scheme-full
    - zlib
    - openssh
    - rsync
    - pkg-config

resolver: lts-20.6

packages:
- .

extra-deps: 
  - hakyll-4.15.1.1
  - stm-2.5.1.0
  - exceptions-0.10.7