name: Haskell CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: freckle/stack-action@v3
      with:
        test: false

    - name: Generate Site
      run: |
        stack build
        stack run -- rebuild
